Moved digests methods and renamed them.
2start/pyback pull request #15
Opened 2019-05-24 11:47 UTC by friedrichschoene

fixes #5

2019-05-24 19:17 UTC, klaudworks reviewed
Okay I think this is better than the previous solution. However, if we use a static method of the TreeNodes to create the TreeNode itself we should probably just create a static factory method inside each TreeNode that builds it.

2019-05-24 19:21 UTC, 2start commented
Okay factory method might be the wrong description. I am talking about a static `build()` method. That calls the checksum method internally and calls the constructor with the checksum.

2019-05-24 20:20 UTC, friedrichschoene commented
Agreed

2019-05-25 19:27 UTC, klaudworks requested changes

2019-05-25 19:27 UTC, 2start commented on bakker/checkpoint.py
> +    @staticmethod
Concentration please.

2019-05-25 19:35 UTC, merged